import { describe, expect, it } from 'vitest'

import {
  deriveLogicalKey,
  hasAutoGeneratedSuffix,
  stripAutoSuffix,
} from '../../../src/connector/logical-key.js'

describe('deriveLogicalKey', () => {
  describe('builtin source', () => {
    it('uses id as-is', () => {
      expect(deriveLogicalKey('builtin', 'filesystem')).toBe('filesystem')
      expect(deriveLogicalKey('builtin', 'shell')).toBe('shell')
      expect(deriveLogicalKey('builtin', 'web_search')).toBe('web_search')
    })

    it('does not strip even when id matches the auto-suffix regex', () => {
      // Builtin ids are stable category names; we never strip.
      expect(deriveLogicalKey('builtin', 'foo-abcdefgh')).toBe('foo-abcdefgh')
    })
  })

  describe('mcp source', () => {
    // Phase 16 (2026-05-01): the legacy `'custom_mcp'` source merged
    // into `'mcp'`. The auto-id-suffix stripping behaviour that used to
    // live under `'custom_mcp'` now lives under `'mcp'` because user-
    // registered rows surface here too. Featured slugs in practice never
    // match the regex (each char in `[a-z2-7]`, exactly 8 chars after a
    // dash) so they pass through unchanged.

    it('uses id as-is for stable registry slugs', () => {
      expect(deriveLogicalKey('mcp', 'notion')).toBe('notion')
      expect(deriveLogicalKey('mcp', 'figma')).toBe('figma')
      expect(deriveLogicalKey('mcp', 'github')).toBe('github')
    })

    it('preserves URN-shaped ids verbatim', () => {
      expect(deriveLogicalKey('mcp', 'io.github.user/weather')).toBe(
        'io.github.user/weather',
      )
    })

    it('strips auto-generated 8-char base32 suffix (user-registered rows)', () => {
      expect(deriveLogicalKey('mcp', 'figma-c4vrjq3w')).toBe('figma')
      expect(deriveLogicalKey('mcp', 'notion-a7f2kmqr')).toBe('notion')
      expect(deriveLogicalKey('mcp', 'my-server-2abc4567')).toBe('my-server')
    })

    it('keeps id when no suffix pattern matches', () => {
      expect(deriveLogicalKey('mcp', 'figma')).toBe('figma')
      expect(deriveLogicalKey('mcp', 'my-tool')).toBe('my-tool')
      expect(deriveLogicalKey('mcp', 'a')).toBe('a')
    })

    it('only strips when last segment is exactly 8 chars', () => {
      // 7 chars
      expect(deriveLogicalKey('mcp', 'figma-abc4567')).toBe('figma-abc4567')
      // 9 chars
      expect(deriveLogicalKey('mcp', 'figma-abc456789')).toBe('figma-abc456789')
    })

    it('only strips when chars are in base32 alphabet [a-z2-7]', () => {
      // Contains '8' (not in alphabet) — no strip
      expect(deriveLogicalKey('mcp', 'figma-abc45678')).toBe('figma-abc45678')
      // Contains '0' (not in alphabet) — no strip
      expect(deriveLogicalKey('mcp', 'figma-abc4567a0')).toBe('figma-abc4567a0')
      // Contains '9' (not in alphabet) — no strip
      expect(deriveLogicalKey('mcp', 'figma-abc4567a9')).toBe('figma-abc4567a9')
      // Contains uppercase — no strip
      expect(deriveLogicalKey('mcp', 'figma-Abcdefgh')).toBe('figma-Abcdefgh')
    })

    it('strips only the trailing suffix when multiple dashes present', () => {
      expect(deriveLogicalKey('mcp', 'my-cool-server-c4vrjq3w')).toBe(
        'my-cool-server',
      )
    })

    it('handles edge case: id IS a suffix pattern (no kebab prefix)', () => {
      // Pure 8-char base32 with no leading dash — the regex requires `-` so
      // it doesn't match. Returned as-is.
      expect(deriveLogicalKey('mcp', 'abcdefgh')).toBe('abcdefgh')
    })
  })

  describe('composio source', () => {
    it('uses toolkit slug as-is', () => {
      expect(deriveLogicalKey('composio', 'gmail')).toBe('gmail')
      expect(deriveLogicalKey('composio', 'google_sheets')).toBe('google_sheets')
      expect(deriveLogicalKey('composio', 'notion')).toBe('notion')
    })
  })

  describe('explicitMap override', () => {
    it('wins over auto-derivation for mcp', () => {
      const map = new Map([['my-server-c4vrjq3w', 'figma']])
      expect(
        deriveLogicalKey('mcp', 'my-server-c4vrjq3w', { explicitMap: map }),
      ).toBe('figma')
    })

    it('wins over identity for stable mcp slugs', () => {
      const map = new Map([['figma-canvas', 'figma']])
      expect(
        deriveLogicalKey('mcp', 'figma-canvas', { explicitMap: map }),
      ).toBe('figma')
    })

    it('wins for builtin too', () => {
      const map = new Map([['filesystem', 'fs']])
      expect(
        deriveLogicalKey('builtin', 'filesystem', { explicitMap: map }),
      ).toBe('fs')
    })

    it('absent map keys fall through to default derivation', () => {
      const map = new Map([['other-id', 'other']])
      expect(
        deriveLogicalKey('mcp', 'figma-c4vrjq3w', { explicitMap: map }),
      ).toBe('figma')
    })

    it('rejects empty mapped value', () => {
      const map = new Map([['my-id', '']])
      expect(() =>
        deriveLogicalKey('mcp', 'my-id', { explicitMap: map }),
      ).toThrow(/non-empty/)
    })
  })

  describe('error cases', () => {
    it('throws on empty id', () => {
      expect(() => deriveLogicalKey('builtin', '')).toThrow(/non-empty/)
      expect(() => deriveLogicalKey('mcp', '')).toThrow(/non-empty/)
      expect(() => deriveLogicalKey('composio', '')).toThrow(/non-empty/)
    })
  })

  describe('determinism', () => {
    it('returns same result across many invocations', () => {
      const results = new Set<string>()
      for (let i = 0; i < 100; i++) {
        results.add(deriveLogicalKey('mcp', 'figma-c4vrjq3w'))
      }
      expect(results.size).toBe(1)
      expect([...results][0]).toBe('figma')
    })
  })
})

describe('hasAutoGeneratedSuffix', () => {
  it('matches valid auto-id format', () => {
    expect(hasAutoGeneratedSuffix('figma-c4vrjq3w')).toBe(true)
    expect(hasAutoGeneratedSuffix('my-server-2abc4567')).toBe(true)
    expect(hasAutoGeneratedSuffix('a-abcdefgh')).toBe(true)
  })

  it('rejects non-matches', () => {
    expect(hasAutoGeneratedSuffix('figma')).toBe(false)
    expect(hasAutoGeneratedSuffix('figma-abc')).toBe(false)
    expect(hasAutoGeneratedSuffix('abcdefgh')).toBe(false) // no leading dash
    expect(hasAutoGeneratedSuffix('figma-Abcdefgh')).toBe(false) // uppercase
    expect(hasAutoGeneratedSuffix('figma-12345678')).toBe(false) // 1 not in alphabet
    expect(hasAutoGeneratedSuffix('figma-abcdefg9')).toBe(false) // 9 not in alphabet
  })
})

describe('stripAutoSuffix', () => {
  it('strips when pattern matches', () => {
    expect(stripAutoSuffix('figma-c4vrjq3w')).toBe('figma')
    expect(stripAutoSuffix('my-cool-server-2abc4567')).toBe('my-cool-server')
  })

  it('returns id unchanged when no pattern', () => {
    expect(stripAutoSuffix('figma')).toBe('figma')
    expect(stripAutoSuffix('figma-abc')).toBe('figma-abc')
  })
})
