/**
 * Logical key derivation — the cross-source identity rule.
 *
 * Problem
 * -------
 * `canonicalId` (`<source>:<id>`) is unique per source but does NOT collapse
 * the SAME logical app across different sources. A user can end up with:
 *   - `mcp:figma`              (curated featured server)
 *   - `custom_mcp:figma-c4vrjq3w` (user added the same server manually)
 *   - `composio:figma`         (Composio's Figma toolkit)
 * Three rows for one logical product. Endpoint-based dedup misses this
 * because each row has a different endpoint URL.
 *
 * Solution
 * --------
 * Every `Connector` carries a `logicalKey` — a stable cross-source name for
 * the underlying app. The lobby groups by `logicalKey`, the dedup pass uses
 * `logicalKey` (combined with `aliases.ts` for explicit cross-source pairings),
 * and the source picker shows variants under one card.
 *
 * Derivation rule (per source)
 * ----------------------------
 * - `builtin`     → `id` IS the logical key (e.g. "filesystem", "shell").
 * - `mcp`         → `id` IS the logical key. MCP server ids come from the
 *                   curated/remote registry; they're stable slugs.
 * - `composio`    → `id` IS the logical key. Composio toolkit slugs are
 *                   stable and aligned with MCP slugs where dual-sourced.
 * - `custom_mcp`  → strip the auto-generated random suffix
 *                   (`-[a-z2-7]{8}$`) introduced by `randomSuffix()` in
 *                   `mcp-register.ts`. So `figma-c4vrjq3w` → `figma`.
 *
 * Why only `custom_mcp` strips: the suffix is OUR convention, applied at
 * registration time to disambiguate user-typed names. We KNOW every
 * `custom_mcp` id has the form `<kebab>-<8-base32>`, so stripping is safe.
 * Other sources may have ids that happen to match the regex (a weather
 * MCP at `io.github.user/weather` doesn't, but a bare slug could) — for
 * them we never strip.
 *
 * Cross-source collapse still uses `aliases.ts`: after deriving per-source
 * logical keys, the alias table merges keys that represent the same product
 * across sources (today the slugs already align, e.g. `notion` on both MCP
 * and Composio, so the alias collapse is a no-op for those — but the field
 * is required for the dedup pass to work without re-deriving).
 */

import type { ConnectorSource } from './schema.js'

/**
 * Format of the random suffix appended by `mcp-register.ts:randomSuffix()`:
 * 8 characters from RFC 4648 base32 alphabet (`[a-z2-7]`).
 *
 * Anchored at end with a leading dash so it only matches the trailing
 * component. Greedy match against `$` ensures one and only one strip.
 */
const AUTO_ID_SUFFIX_REGEX = /-[a-z2-7]{8}$/

export interface LogicalKeyHints {
  /**
   * Explicit id-to-logical-key mapping. Highest precedence — wins over any
   * derivation. Use when the source provider has out-of-band knowledge that
   * a particular id maps to a known app (e.g. auto-detect resolved a custom
   * server's endpoint to a `known-apps.json` entry).
   */
  readonly explicitMap?: ReadonlyMap<string, string>
}

/**
 * Derive the logical key for a connector.
 *
 * Pure function. No I/O. Deterministic given (source, id, hints).
 *
 * @throws if `id` is empty (a Connector with no id is invalid by schema).
 */
export function deriveLogicalKey(
  source: ConnectorSource,
  id: string,
  hints: LogicalKeyHints = {},
): string {
  if (id.length === 0) {
    throw new Error('deriveLogicalKey: id must be non-empty')
  }

  // Explicit override always wins.
  const override = hints.explicitMap?.get(id)
  if (override !== undefined) {
    if (override.length === 0) {
      throw new Error(
        `deriveLogicalKey: explicitMap value for id '${id}' must be non-empty`,
      )
    }
    return override
  }

  // Strip the auto-generated suffix only for `mcp` rows whose id matches
  // the auto-id pattern. Pre-Phase 17 (2026-05-01) this was scoped to the
  // now-removed `custom_mcp` source; after the unification, user-
  // registered MCP rows live under `'mcp'` with ids like `figma-c4vrjq3w`,
  // and the catalog needs to collapse those onto the canonical
  // `figma` logical key for grouping with featured entries.
  if (source === 'mcp' && AUTO_ID_SUFFIX_REGEX.test(id)) {
    return id.replace(AUTO_ID_SUFFIX_REGEX, '')
  }

  return id
}

/**
 * True if `id` ends with the auto-generated random suffix pattern. Useful for
 * UI guards that want to reject leaking a raw auto-id to a user-facing field.
 */
export function hasAutoGeneratedSuffix(id: string): boolean {
  return AUTO_ID_SUFFIX_REGEX.test(id)
}

/**
 * Strip the auto-generated suffix unconditionally. Use when you have already
 * established that `id` is a `custom_mcp` row's id (e.g. inside a migration
 * that knows it's working on `mcp_servers` rows where `registry_id = 'custom'`
 * or `'detected'`). For derivation from a `Connector`, prefer
 * `deriveLogicalKey(source, id, hints)` so the source check is enforced.
 */
export function stripAutoSuffix(id: string): string {
  return id.replace(AUTO_ID_SUFFIX_REGEX, '')
}
